name: ai_resume_builder
description: "An AI-powered Resume Builder application with MVVM architecture and BLoC state management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # Routing
  go_router: ^13.0.0
  # Dependency Injection
  get_it: ^7.6.4
  # Functional Programming
  dartz: ^0.10.1
  # Local Storage
  shared_preferences: ^2.2.2
  # HTTP Client
  dio: ^5.4.0
  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  # Icons
  iconsax: ^0.0.8
  feather_icons: ^1.2.0
  # Utils
  equatable: ^2.0.5
  logger: ^2.0.2+1
  intl: ^0.19.0
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  # Supabase
  supabase_flutter: ^2.0.2
  # Environment Configuration
  flutter_dotenv: ^5.1.0
  # Social Sign In
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  linkedin_login: ^2.3.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Testing
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1F2937"
  image: assets/images/logo.png
  image_dark: assets/images/logo_dark.png
  
  android_12:
    color: "#FFFFFF"
    color_dark: "#1F2937"
    image: assets/images/logo.png
    image_dark: assets/images/logo_dark.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#1F2937"

  web: true
  android: true
  ios: true
  
  fullscreen: true
  
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'
